### ISSUE TITLE
Alternate Logo

### ISSUE THREAD

**Issue by bigcfk** [uwmadisoncals/uw-madison-wp-2015#1]
Inside of Appearance > Customizer > Header Image

When selected, the logo doesn't appear anywhere.

**Comment by althe3rd** [comment]
The logo appears for me when performing that action. But that may be due to the particular logo I have chosen?

**Comment by bigcfk** [comment]
It works for me with the default, but not after uploading an alternate logo.

**Comment by bigcfk** [comment]
The alternate logo should prompt users to crop it to scale, too.

**Comment by althe3rd** [comment]
I haven't adjusted the way the controls look on the customizer side yet but i did apply a css fix to the proper logo being assigned when missing an alternative logo.

**Comment by althe3rd** [comment]
I have issues with both normal and alternative logo with cropping.  I like the idea of cropping but wordpress doesn't understand svg's enough and when it suggests a crop for an svg its makes it 0x0.

**Comment by althe3rd** [comment]
This has been overhauled in a recent commit, closing this one for now.
