### ISSUE TITLE
Bulleted lists no longer working in sandbox

### ISSUE THREAD

**Issue by sueryan** [uwmadisoncals/uw-madison-wp-2015#11]
I see them on the back end with I paste or code them in, but when I view the page they are gone.
EX: https://admin.cals.wisc.edu/about-cals/strategic-planning-a-progress-report/
Each section has a lead sentence and the rest below that are bulleted lists

**Comment by althe3rd** [comment]
Good call on this one. I am taking a look now and applying some updated styles soon.

**Comment by althe3rd** [comment]
The bullet styles have been applied along with corresponding editor styles
