### ISSUE TITLE
Header Style: Transparent vs. 'Hero Image from Homepage'

### ISSUE THREAD

**Issue by bigcfk** [uwmadisoncals/uw-madison-wp-2015#2]
Customizer > Header Options > Header Style

It should be noted that this transparency only happens on the homepage.

The option "Hero Image from Homepage" provides a transparent option on other pages.

These could be combined

**Comment by althe3rd** [comment]
Yea I can certainly see why thats confusing.  I get the feeling we should rename the "transparent" option as its actually solid red on sub pages.  Those two are different style options but the naming is not correct.

it wasn't originally solid, hence why it doesn't make any sense now.

**Comment by bigcfk** [comment]
I've changed it to "Red on Subpages" (for Transparent), and "Red on All Pages" (for Opaque). But if Header Slides are disable, they're the same.

This needs new phrasing, and I think should be tied to logic regarding Header Slides.

**Comment by bigcfk** [comment]
This has been addressed in new Customizer groupings.
