### ISSUE TITLE
Custom Logo issues

### ISSUE THREAD

**Issue by bigcfk** [uwmadisoncals/uw-madison-wp-2015#7]
When using Right Anchored Nav Layout & setting Custom Logo to Center = no display. 
Right Anchored Nav & setting Custom Logo to Top Left = displays fine.

When using Navigation Bar Layout, no Custom Logo at all.

**Comment by althe3rd** [comment]
I have just committed a fix to the logo image issues.

**Comment by althe3rd** [comment]
I'll close the issue ticket for now but lets re open it if anything else is discovered thats related.
